name: Webxdc CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        if: hashFiles('package.json') != ''
        uses: pnpm/action-setup@v2

      - name: Setup node
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        if: hashFiles('package.json') != ''
        run: pnpm i

      - name: Build
        if: hashFiles('package.json') != ''
        run: pnpm run build

      - id: check-tag
        run: |
          if [[ "${{ github.event.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi

      - name: Release
        if: hashFiles('manifest.toml') != '' && ${{ github.event_name == 'push' && steps.check-tag.outputs.match == 'true' }}
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Auto-generated release
          prerelease: ${{ contains(github.event.ref, '-beta') }}
          fail_on_unmatched_files: true
          files: dist/*.xdc
